name: Variable Test
on:
  workflow_dispatch
env:
  env_var: dev
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    environment: dev
    env:
      Greeting: Hello
      my-dummy-aws-token: 12d78cd
      login-password: ns-password
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting SP_USERNAME ${{vars.SP_USERNAME1}} SP_PASSWORD ${{secrets.SP_PASSWORD1}} $login-password"
        
